feat: Add Geospatial query support
algolia/algoliasearch-helper-flutter pull request #105
Opened 2023-09-20 10:56 UTC by Wackymax

| Q               | A        |
|-----------------|----------|
| Bug fix?        | no   |
| New feature?    | yes   |
| BC breaks?      | no       |
| Related Issue   | #72  |
| Need Doc update | yes   |

## Describe your change

his commit refactors the SearchState class to include new properties for location-based search parameters. The changes include adding support for aroundLatLngViaIP, aroundLatLng, aroundRadius, minimumAroundRadius, aroundPrecision, and boundingbox.

This also updates the dependencies to use ranges so that projects relying on this one don't run into inter dependency lock issues.

## What problem is this fixing?

2023-09-22 15:44 UTC, VladislavFitz requested changes
Thanks for a great contribution @Wackymax !
Could you rollback all the release-related changes since we have a special release process that we run on our own. I'll keep the changelog updates you added.

2023-09-22 15:44 UTC, VladislavFitz commented on helper/lib/src/lib_version.dart
> +const libVersion = '0.5.0';
```suggestion
const libVersion = '0.4.1';
```

2023-10-02 10:08 UTC, VladislavFitz requested changes
There are some last minor fixes left, otherwise looks great.

2023-10-02 10:08 UTC, VladislavFitz commented on helper/pubspec.yaml
> +version: 0.5.0
```suggestion
version: 0.4.1
```

2023-10-02 10:08 UTC, VladislavFitz commented on insights/pubspec.yaml
> +version: 0.2.2
```suggestion
version: 0.2.1
```

2023-10-02 10:08 UTC, VladislavFitz commented on CHANGELOG.md
> -
Restore the trailing line here to prevent this file from showing up in the diff.

2023-10-02 13:47 UTC, VladislavFitz approved these changes

2023-10-02 13:48 UTC, merged

2023-10-03 14:08 UTC, Wackymax commented
@VladislavFitz regrettably this isn't working 100%. I am getting the following when specifying the bounding box params:
`"message":"Invalid value for \"insideBoundingBox\" parameter, expected float","status":400`

Seems to be related to the algolia internal libs though

2023-10-11 13:48 UTC, VladislavFitz commented
@Wackymax the issue in the Dart client has been fixed. Could you check if it works properly on your end now?

2023-10-11 13:52 UTC, Wackymax commented
Thank you. I will check and let you know if I continue to encounter the error.On 11 Oct 2023, at 15:48, Vladislav Fitc ***@***.***> wrote:﻿
@Wackymax the issue in the Dart client has been fixed. Could you check if it works properly on your end now?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>