feat: MultiSearcher and FacetSearcher
algolia/algoliasearch-helper-flutter pull request #92
Opened 2023-07-28 12:07 UTC by VladislavFitz

| Q               | A        |
|-----------------|----------|
| Bug fix?        | no   |
| New feature?    | yes   |
| BC breaks?      | no       |
| Need Doc update | yes   |

## Describe your change

Adds `MultiSearcher` and `FacetSearcher` components.

2023-08-02 12:09 UTC, aallam commented on helper_dart/lib/src/searcher/multi_searcher.dart
> +      (states) => states.cast<MultiSearchState>(),
I think this can simply be `(states) => states`

2023-08-09 12:39 UTC, VladislavFitz commented on insights_dart/lib/src/algolia_event_service.dart
> +          InsightsClient(
I made it customizable on the Insights level.

2023-08-31 16:38 UTC, VladislavFitz commented on helper_dart/lib/src/searcher/facet_searcher.dart
> +abstract class FacetSearcher implements Disposable {
Done ✅

2023-08-31 16:54 UTC, VladislavFitz commented on helper_dart/lib/src/service/algolia_client_helper.dart
> +      );
Done ✔️

2023-08-31 20:05 UTC, VladislavFitz commented on helper_dart/lib/src/searcher/multi_searcher.dart
> +        .listen((responses) {
It's done on the service layer (Facet/Hits/MultiSearchService).

2023-09-04 12:06 UTC, VladislavFitz commented
@aallam I've applied most of your suggestions and added examples. Can you run through the code again?

2023-09-04 14:34 UTC, aallam requested changes
Very nice refactoring! I've left a few last small suggestions :)

2023-09-04 14:34 UTC, aallam commented on insights/lib/src/algolia_event_service.dart
> +                  value: 'algolia-insights-dart',
Same here! ;D

2023-09-04 14:41 UTC, VladislavFitz commented on helper/lib/src/searcher/multi_searcher.dart
> +    required SearchState initialState,
I also thought about that. I would add some simplified methods, like `addHitsSearcher(String indexName)`/ `addFacetSearcher(String indexName, String facetAttribute)` which perform basic state initialization, but there is no method overloading in Dart. For standalone Hits/FacetSearcher we use constructors with different parameters. Do you have any ideas? Maybe different method names?

2023-09-04 14:42 UTC, VladislavFitz commented on helper/lib/src/service/algolia_facet_search_service.dart
> +                  value: 'algolia-helper-dart',
Will discuss it with Patrick since it will require monitoring tools update as well.

2023-09-04 14:50 UTC, VladislavFitz commented on helper/example/facet_searcher.dart
> +    facet: 'MY_FACET_ATTRIBUTE',
Done ✅

2023-09-04 14:50 UTC, VladislavFitz commented on helper/lib/src/service/algolia_facet_search_service.dart
> +                  value: 'algolia-helper-dart',
@patrick-loomis wdyt?

2023-09-04 14:54 UTC, VladislavFitz commented on helper/lib/src/searcher/multi_searcher.dart
> +  final Logger _log = algoliaLogger('MultiSearcher');
Done ✅

2023-09-04 14:55 UTC, VladislavFitz commented on insights/mono_pkg.yaml
Done 👍

2023-09-04 16:10 UTC, VladislavFitz commented on insights/pubspec.lock
Done ✅

2023-09-04 16:21 UTC, aallam commented on helper/lib/src/searcher/multi_searcher.dart
> +    required SearchState initialState,
Yes indeed, we will need different names to make this work, maybe something like `createHitsSearcher` or `registerHitsSearcher` ?

2023-09-04 17:12 UTC, VladislavFitz commented on insights_dart/lib/src/lib_version.dart
> +const libVersion = '0.1.1';
Added script, hook and tests.

2023-09-04 17:13 UTC, VladislavFitz commented on insights/lib/src/lib_version.dart
> +const libVersion = '0.1.1';
Fixed

2023-09-05 13:55 UTC, VladislavFitz commented on insights/lib/src/algolia_event_service.dart
> +                  value: 'algolia-insights-dart',
Done

2023-09-05 13:55 UTC, VladislavFitz commented on helper/lib/src/service/algolia_hits_search_service.dart
> +                  value: 'algolia-helper-dart',
Done

2023-09-05 13:55 UTC, VladislavFitz commented on helper/lib/src/service/algolia_facet_search_service.dart
> +                  value: 'algolia-helper-dart',
Done

2023-09-05 13:56 UTC, VladislavFitz commented on helper/lib/src/searcher/multi_searcher.dart
> +    required SearchState initialState,
I keep it as is for now, we can always add some convenience layer later.

2023-09-05 14:36 UTC, aallam approved these changes
Huge effort! GJ! 🚀

2023-09-05 14:56 UTC, merged